INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (101,'Pooja Jain','Female',52,'Jaipur','Rajasthan','2024-04-07');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (102,'Anjali Verma','Female',50,'Delhi','Delhi','2024-06-08');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (103,'Arjun Mehta','Male',48,'Delhi','Delhi','2023-04-07');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (104,'Vikas Singh','Male',60,'Pune','Maharashtra','2024-07-05');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (105,'Rahul Mehta','Male',59,'Ahmedabad','Gujarat','2024-04-08');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (106,'Arjun Singh','Male',24,'Mumbai','Maharashtra','2024-06-25');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (107,'Rahul Sharma','Male',58,'Bengaluru','Karnataka','2023-09-05');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (108,'Rahul Kumar','Male',57,'Chennai','Tamil Nadu','2024-03-27');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (109,'Sneha Jain','Female',38,'Bengaluru','Karnataka','2024-10-17');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (110,'Pooja Sharma','Female',37,'Pune','Maharashtra','2024-04-13');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (111,'Rohan Jain','Male',40,'Pune','Maharashtra','2023-09-18');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (112,'Sneha Jain','Female',24,'Hyderabad','Telangana','2023-01-31');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (113,'Anjali Patel','Female',38,'Ahmedabad','Gujarat','2023-04-21');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (114,'Rohan Patel','Male',33,'Mumbai','Maharashtra','2023-01-01');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (115,'Sneha Sharma','Female',45,'Jaipur','Rajasthan','2024-01-20');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (116,'Rohan Patel','Male',37,'Bengaluru','Karnataka','2024-11-22');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (117,'Neha Patel','Female',20,'Hyderabad','Telangana','2023-12-07');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (118,'Rohan Patel','Male',26,'Delhi','Delhi','2023-09-10');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (119,'Rahul Sharma','Male',31,'Jaipur','Rajasthan','2024-05-13');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (120,'Arjun Jain','Male',52,'Bengaluru','Karnataka','2024-04-03');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (121,'Sneha Singh','Female',44,'Ahmedabad','Gujarat','2024-10-21');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (122,'Priya Joshi','Female',20,'Ahmedabad','Gujarat','2023-08-06');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (123,'Vikas Mehta','Male',33,'Hyderabad','Telangana','2023-01-21');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (124,'Amit Joshi','Male',29,'Pune','Maharashtra','2023-02-13');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (125,'Sneha Kumar','Female',59,'Hyderabad','Telangana','2023-01-10');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (126,'Neha Gupta','Female',24,'Ahmedabad','Gujarat','2023-03-17');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (127,'Priya Verma','Female',58,'Bengaluru','Karnataka','2023-01-16');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (128,'Neha Patil','Female',57,'Jaipur','Rajasthan','2023-05-11');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (129,'Pooja Mehta','Female',31,'Delhi','Delhi','2024-01-31');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (130,'Arjun Singh','Male',59,'Hyderabad','Telangana','2023-08-22');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (131,'Sneha Verma','Female',55,'Delhi','Delhi','2024-10-06');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (132,'Sneha Joshi','Female',25,'Jaipur','Rajasthan','2024-09-10');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (133,'Rohan Sharma','Male',22,'Pune','Maharashtra','2023-04-22');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (134,'Karan Gupta','Male',36,'Bengaluru','Karnataka','2024-02-06');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (135,'Rohan Mehta','Male',53,'Jaipur','Rajasthan','2023-10-28');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (136,'Amit Patel','Male',50,'Delhi','Delhi','2023-08-22');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (137,'Karan Mehta','Male',33,'Pune','Maharashtra','2023-10-14');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (138,'Sneha Sharma','Female',46,'Pune','Maharashtra','2023-10-03');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (139,'Pooja Verma','Female',31,'Mumbai','Maharashtra','2023-02-17');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (140,'Vikas Patil','Male',43,'Delhi','Delhi','2023-04-05');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (141,'Amit Kumar','Male',53,'Chennai','Tamil Nadu','2024-11-03');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (142,'Anjali Singh','Female',50,'Mumbai','Maharashtra','2023-01-19');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (143,'Neha Gupta','Female',58,'Mumbai','Maharashtra','2023-01-22');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (144,'Arjun Patel','Male',39,'Jaipur','Rajasthan','2023-03-10');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (145,'Neha Singh','Female',48,'Pune','Maharashtra','2023-03-19');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (146,'Karan Patil','Male',41,'Mumbai','Maharashtra','2023-05-13');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (147,'Neha Patel','Female',46,'Jaipur','Rajasthan','2023-03-21');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (148,'Rahul Kumar','Male',44,'Mumbai','Maharashtra','2024-10-01');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (149,'Rohan Mehta','Male',24,'Mumbai','Maharashtra','2024-09-15');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (150,'Priya Patel','Female',46,'Pune','Maharashtra','2023-09-21');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (151,'Kavya Patil','Female',49,'Ahmedabad','Gujarat','2024-08-17');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (152,'Pooja Kumar','Female',52,'Pune','Maharashtra','2024-06-15');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (153,'Rahul Gupta','Male',21,'Pune','Maharashtra','2024-05-07');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (154,'Sneha Patel','Female',51,'Jaipur','Rajasthan','2024-09-21');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (155,'Vikas Sharma','Male',29,'Chennai','Tamil Nadu','2023-11-05');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (156,'Arjun Mehta','Male',30,'Bengaluru','Karnataka','2024-06-14');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (157,'Neha Kumar','Female',40,'Jaipur','Rajasthan','2023-09-05');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (158,'Rohan Gupta','Male',47,'Bengaluru','Karnataka','2024-10-11');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (159,'Sneha Verma','Female',57,'Ahmedabad','Gujarat','2023-08-13');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (160,'Neha Verma','Female',51,'Delhi','Delhi','2023-05-18');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (161,'Neha Sharma','Female',30,'Pune','Maharashtra','2023-10-11');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (162,'Priya Kumar','Female',33,'Jaipur','Rajasthan','2023-10-09');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (163,'Rohan Joshi','Male',40,'Jaipur','Rajasthan','2024-11-19');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (164,'Kavya Mehta','Female',24,'Jaipur','Rajasthan','2023-11-25');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (165,'Rahul Gupta','Male',37,'Mumbai','Maharashtra','2024-11-25');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (166,'Anjali Patil','Female',56,'Hyderabad','Telangana','2024-10-26');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (167,'Rahul Singh','Male',32,'Ahmedabad','Gujarat','2024-04-10');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (168,'Rahul Gupta','Male',23,'Bengaluru','Karnataka','2023-05-25');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (169,'Arjun Patel','Male',60,'Jaipur','Rajasthan','2023-04-22');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (170,'Karan Patil','Male',32,'Pune','Maharashtra','2024-12-01');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (171,'Sneha Kumar','Female',20,'Hyderabad','Telangana','2023-07-02');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (172,'Pooja Jain','Female',34,'Mumbai','Maharashtra','2023-07-03');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (173,'Vikas Patil','Male',34,'Delhi','Delhi','2024-02-07');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (174,'Priya Joshi','Female',48,'Ahmedabad','Gujarat','2023-05-14');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (175,'Pooja Verma','Female',55,'Mumbai','Maharashtra','2024-01-21');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (176,'Anjali Jain','Female',40,'Chennai','Tamil Nadu','2024-04-19');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (177,'Arjun Verma','Male',27,'Pune','Maharashtra','2024-10-19');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (178,'Sneha Verma','Female',39,'Ahmedabad','Gujarat','2023-03-31');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (179,'Karan Patil','Male',42,'Hyderabad','Telangana','2023-01-17');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (180,'Karan Patel','Male',41,'Mumbai','Maharashtra','2024-03-27');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (181,'Karan Joshi','Male',21,'Hyderabad','Telangana','2024-05-14');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (182,'Sneha Patel','Female',31,'Ahmedabad','Gujarat','2023-02-05');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (183,'Karan Patil','Male',29,'Delhi','Delhi','2024-04-26');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (184,'Karan Jain','Male',57,'Jaipur','Rajasthan','2024-05-19');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (185,'Kavya Patel','Female',53,'Bengaluru','Karnataka','2024-03-25');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (186,'Karan Gupta','Male',52,'Delhi','Delhi','2024-06-19');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (187,'Karan Gupta','Male',44,'Hyderabad','Telangana','2024-11-18');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (188,'Anjali Verma','Female',54,'Hyderabad','Telangana','2023-05-25');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (189,'Karan Gupta','Male',46,'Jaipur','Rajasthan','2023-07-25');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (190,'Karan Patel','Male',44,'Mumbai','Maharashtra','2024-09-11');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (191,'Rahul Jain','Male',45,'Mumbai','Maharashtra','2024-06-12');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (192,'Karan Mehta','Male',25,'Pune','Maharashtra','2024-05-17');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (193,'Kavya Singh','Female',49,'Pune','Maharashtra','2024-07-05');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (194,'Rohan Joshi','Male',50,'Hyderabad','Telangana','2023-09-10');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (195,'Pooja Singh','Female',50,'Chennai','Tamil Nadu','2024-03-20');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (196,'Karan Patil','Male',46,'Pune','Maharashtra','2023-07-16');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (197,'Anjali Sharma','Female',21,'Hyderabad','Telangana','2023-05-13');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (198,'Rahul Verma','Male',20,'Delhi','Delhi','2023-08-21');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (199,'Arjun Gupta','Male',35,'Chennai','Tamil Nadu','2023-12-30');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (200,'Anjali Kumar','Female',57,'Pune','Maharashtra','2024-05-26');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (201,'Priya Jain','Female',53,'Hyderabad','Telangana','2023-07-22');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (202,'Rohan Sharma','Male',46,'Ahmedabad','Gujarat','2024-10-10');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (203,'Karan Mehta','Male',33,'Delhi','Delhi','2024-07-05');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (204,'Arjun Jain','Male',33,'Bengaluru','Karnataka','2024-06-26');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (205,'Karan Mehta','Male',60,'Delhi','Delhi','2023-08-27');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (206,'Neha Singh','Female',40,'Chennai','Tamil Nadu','2024-09-09');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (207,'Sneha Verma','Female',28,'Bengaluru','Karnataka','2023-04-10');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (208,'Sneha Singh','Female',44,'Pune','Maharashtra','2023-09-23');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (209,'Priya Joshi','Female',28,'Ahmedabad','Gujarat','2024-07-10');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (210,'Sneha Joshi','Female',32,'Mumbai','Maharashtra','2023-04-09');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (211,'Anjali Patil','Female',52,'Chennai','Tamil Nadu','2023-04-29');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (212,'Arjun Patil','Male',50,'Bengaluru','Karnataka','2023-03-14');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (213,'Priya Sharma','Female',59,'Mumbai','Maharashtra','2024-07-18');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (214,'Karan Mehta','Male',32,'Jaipur','Rajasthan','2023-05-31');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (215,'Amit Patel','Male',30,'Bengaluru','Karnataka','2023-06-26');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (216,'Vikas Patel','Male',49,'Mumbai','Maharashtra','2023-05-18');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (217,'Priya Patel','Female',49,'Chennai','Tamil Nadu','2024-02-05');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (218,'Rohan Jain','Male',33,'Chennai','Tamil Nadu','2024-03-16');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (219,'Anjali Patil','Female',22,'Mumbai','Maharashtra','2024-10-11');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (220,'Sneha Singh','Female',43,'Ahmedabad','Gujarat','2024-04-09');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (221,'Kavya Patil','Female',58,'Ahmedabad','Gujarat','2023-07-19');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (222,'Amit Patel','Male',25,'Mumbai','Maharashtra','2023-11-28');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (223,'Kavya Joshi','Female',57,'Bengaluru','Karnataka','2024-05-31');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (224,'Neha Gupta','Female',30,'Hyderabad','Telangana','2023-04-30');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (225,'Rohan Singh','Male',43,'Chennai','Tamil Nadu','2024-07-05');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (226,'Rohan Singh','Male',31,'Ahmedabad','Gujarat','2023-07-31');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (227,'Priya Patil','Female',26,'Hyderabad','Telangana','2024-04-25');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (228,'Rahul Patil','Male',37,'Mumbai','Maharashtra','2023-08-26');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (229,'Arjun Gupta','Male',45,'Chennai','Tamil Nadu','2023-08-10');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (230,'Anjali Singh','Female',52,'Pune','Maharashtra','2024-02-03');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (231,'Pooja Verma','Female',56,'Pune','Maharashtra','2024-02-09');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (232,'Rahul Patel','Male',36,'Pune','Maharashtra','2023-08-31');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (233,'Pooja Joshi','Female',44,'Mumbai','Maharashtra','2023-07-20');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (234,'Rahul Patel','Male',37,'Hyderabad','Telangana','2023-09-14');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (235,'Neha Jain','Female',56,'Ahmedabad','Gujarat','2024-06-17');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (236,'Priya Kumar','Female',58,'Pune','Maharashtra','2024-07-16');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (237,'Arjun Sharma','Male',44,'Ahmedabad','Gujarat','2023-06-13');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (238,'Pooja Singh','Female',59,'Jaipur','Rajasthan','2024-07-08');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (239,'Anjali Sharma','Female',46,'Ahmedabad','Gujarat','2024-05-21');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (240,'Vikas Jain','Male',39,'Ahmedabad','Gujarat','2024-09-04');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (241,'Neha Jain','Female',37,'Hyderabad','Telangana','2024-05-09');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (242,'Karan Gupta','Male',20,'Hyderabad','Telangana','2023-01-28');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (243,'Sneha Mehta','Female',30,'Mumbai','Maharashtra','2024-10-10');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (244,'Rohan Joshi','Male',45,'Mumbai','Maharashtra','2023-11-19');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (245,'Rahul Mehta','Male',34,'Chennai','Tamil Nadu','2023-03-17');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (246,'Rohan Kumar','Male',22,'Hyderabad','Telangana','2023-09-07');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (247,'Karan Patel','Male',35,'Jaipur','Rajasthan','2023-05-28');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (248,'Anjali Patel','Female',46,'Mumbai','Maharashtra','2024-10-01');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (249,'Pooja Patel','Female',42,'Bengaluru','Karnataka','2023-02-23');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (250,'Karan Singh','Male',48,'Pune','Maharashtra','2024-01-08');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (251,'Amit Joshi','Male',36,'Jaipur','Rajasthan','2024-09-07');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (252,'Arjun Mehta','Male',53,'Ahmedabad','Gujarat','2024-01-08');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (253,'Amit Gupta','Male',50,'Delhi','Delhi','2023-09-02');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (254,'Priya Jain','Female',59,'Hyderabad','Telangana','2024-06-03');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (255,'Neha Gupta','Female',56,'Hyderabad','Telangana','2024-09-16');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (256,'Kavya Mehta','Female',37,'Bengaluru','Karnataka','2024-10-10');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (257,'Sneha Verma','Female',32,'Bengaluru','Karnataka','2024-05-29');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (258,'Arjun Sharma','Male',37,'Mumbai','Maharashtra','2023-01-10');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (259,'Vikas Joshi','Male',22,'Mumbai','Maharashtra','2024-09-30');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (260,'Priya Verma','Female',25,'Hyderabad','Telangana','2023-03-16');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (261,'Arjun Singh','Male',43,'Bengaluru','Karnataka','2024-10-08');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (262,'Pooja Kumar','Female',41,'Chennai','Tamil Nadu','2023-08-04');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (263,'Neha Kumar','Female',27,'Delhi','Delhi','2023-03-18');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (264,'Pooja Mehta','Female',47,'Bengaluru','Karnataka','2024-03-31');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (265,'Kavya Gupta','Female',43,'Ahmedabad','Gujarat','2023-06-04');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (266,'Amit Mehta','Male',55,'Chennai','Tamil Nadu','2023-10-25');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (267,'Kavya Singh','Female',43,'Ahmedabad','Gujarat','2024-10-31');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (268,'Anjali Patel','Female',25,'Jaipur','Rajasthan','2023-11-28');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (269,'Karan Patel','Male',56,'Ahmedabad','Gujarat','2024-07-31');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (270,'Pooja Kumar','Female',24,'Hyderabad','Telangana','2023-01-10');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (271,'Vikas Verma','Male',51,'Pune','Maharashtra','2023-11-08');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (272,'Kavya Patil','Female',34,'Hyderabad','Telangana','2023-05-27');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (273,'Neha Patil','Female',40,'Chennai','Tamil Nadu','2023-05-01');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (274,'Kavya Kumar','Female',53,'Hyderabad','Telangana','2024-03-24');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (275,'Vikas Kumar','Male',45,'Chennai','Tamil Nadu','2023-08-15');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (276,'Kavya Jain','Female',43,'Bengaluru','Karnataka','2023-03-28');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (277,'Neha Sharma','Female',45,'Chennai','Tamil Nadu','2024-11-24');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (278,'Anjali Joshi','Female',43,'Bengaluru','Karnataka','2024-07-31');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (279,'Rohan Jain','Male',56,'Delhi','Delhi','2024-08-28');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (280,'Amit Singh','Male',38,'Pune','Maharashtra','2024-04-10');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (281,'Rahul Verma','Male',30,'Mumbai','Maharashtra','2024-07-11');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (282,'Anjali Gupta','Female',47,'Mumbai','Maharashtra','2024-10-28');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (283,'Priya Mehta','Female',25,'Hyderabad','Telangana','2024-07-12');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (284,'Neha Patel','Female',40,'Hyderabad','Telangana','2023-04-18');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (285,'Priya Sharma','Female',47,'Delhi','Delhi','2023-04-10');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (286,'Sneha Verma','Female',41,'Jaipur','Rajasthan','2024-06-18');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (287,'Pooja Joshi','Female',41,'Chennai','Tamil Nadu','2023-12-12');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (288,'Arjun Singh','Male',54,'Jaipur','Rajasthan','2024-05-14');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (289,'Kavya Patel','Female',42,'Mumbai','Maharashtra','2024-02-25');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (290,'Rahul Joshi','Male',54,'Pune','Maharashtra','2024-04-20');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (291,'Arjun Sharma','Male',27,'Chennai','Tamil Nadu','2023-01-11');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (292,'Rohan Joshi','Male',30,'Delhi','Delhi','2023-09-09');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (293,'Arjun Joshi','Male',33,'Delhi','Delhi','2023-11-25');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (294,'Rohan Joshi','Male',23,'Hyderabad','Telangana','2023-10-08');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (295,'Pooja Gupta','Female',29,'Pune','Maharashtra','2023-11-07');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (296,'Amit Sharma','Male',57,'Jaipur','Rajasthan','2023-01-18');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (297,'Pooja Sharma','Female',32,'Chennai','Tamil Nadu','2023-04-22');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (298,'Amit Patil','Male',35,'Bengaluru','Karnataka','2024-08-25');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (299,'Anjali Kumar','Female',31,'Bengaluru','Karnataka','2024-03-28');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (300,'Vikas Joshi','Male',60,'Delhi','Delhi','2023-11-16');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (301,'Karan Jain','Male',51,'Jaipur','Rajasthan','2023-09-24');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (302,'Rohan Patil','Male',34,'Pune','Maharashtra','2024-05-09');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (303,'Rohan Sharma','Male',44,'Bengaluru','Karnataka','2023-05-18');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (304,'Karan Jain','Male',35,'Hyderabad','Telangana','2023-03-01');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (305,'Rahul Kumar','Male',35,'Chennai','Tamil Nadu','2024-04-05');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (306,'Kavya Joshi','Female',30,'Delhi','Delhi','2024-03-01');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (307,'Neha Singh','Female',28,'Hyderabad','Telangana','2024-06-12');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (308,'Arjun Mehta','Male',54,'Hyderabad','Telangana','2024-06-12');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (309,'Rahul Singh','Male',33,'Delhi','Delhi','2023-01-02');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (310,'Amit Singh','Male',37,'Pune','Maharashtra','2023-12-27');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (311,'Anjali Jain','Female',49,'Pune','Maharashtra','2024-05-06');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (312,'Priya Mehta','Female',32,'Hyderabad','Telangana','2023-01-20');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (313,'Rohan Verma','Male',33,'Pune','Maharashtra','2024-03-26');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (314,'Rahul Jain','Male',51,'Ahmedabad','Gujarat','2024-06-22');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (315,'Amit Gupta','Male',45,'Chennai','Tamil Nadu','2023-11-15');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (316,'Priya Jain','Female',24,'Hyderabad','Telangana','2024-04-23');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (317,'Neha Patel','Female',45,'Delhi','Delhi','2023-04-19');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (318,'Arjun Kumar','Male',48,'Pune','Maharashtra','2024-10-31');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (319,'Rahul Joshi','Male',38,'Jaipur','Rajasthan','2023-09-01');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (320,'Anjali Patel','Female',33,'Jaipur','Rajasthan','2023-01-11');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (321,'Anjali Singh','Female',44,'Hyderabad','Telangana','2024-10-04');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (322,'Karan Gupta','Male',55,'Chennai','Tamil Nadu','2024-02-06');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (323,'Arjun Patel','Male',32,'Hyderabad','Telangana','2023-07-13');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (324,'Rohan Patel','Male',37,'Chennai','Tamil Nadu','2023-11-14');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (325,'Anjali Kumar','Female',44,'Chennai','Tamil Nadu','2024-04-02');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (326,'Priya Patel','Female',26,'Delhi','Delhi','2024-09-28');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (327,'Amit Singh','Male',45,'Delhi','Delhi','2023-07-17');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (328,'Rahul Kumar','Male',34,'Pune','Maharashtra','2023-04-13');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (329,'Rahul Singh','Male',46,'Pune','Maharashtra','2024-03-20');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (330,'Priya Patil','Female',28,'Ahmedabad','Gujarat','2024-06-07');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (331,'Arjun Verma','Male',50,'Delhi','Delhi','2024-01-31');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (332,'Neha Joshi','Female',59,'Mumbai','Maharashtra','2024-02-15');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (333,'Kavya Patil','Female',58,'Bengaluru','Karnataka','2024-11-07');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (334,'Karan Sharma','Male',32,'Hyderabad','Telangana','2023-12-05');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (335,'Neha Gupta','Female',55,'Jaipur','Rajasthan','2023-04-19');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (336,'Rohan Verma','Male',26,'Chennai','Tamil Nadu','2023-10-28');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (337,'Anjali Singh','Female',39,'Hyderabad','Telangana','2024-07-05');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (338,'Karan Verma','Male',52,'Chennai','Tamil Nadu','2024-09-18');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (339,'Karan Singh','Male',32,'Bengaluru','Karnataka','2024-06-12');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (340,'Anjali Sharma','Female',28,'Bengaluru','Karnataka','2023-03-27');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (341,'Sneha Kumar','Female',41,'Ahmedabad','Gujarat','2023-12-08');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (342,'Priya Patil','Female',27,'Hyderabad','Telangana','2024-04-19');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (343,'Pooja Singh','Female',54,'Bengaluru','Karnataka','2024-08-05');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (344,'Karan Jain','Male',36,'Pune','Maharashtra','2024-07-27');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (345,'Amit Patil','Male',20,'Delhi','Delhi','2023-05-06');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (346,'Vikas Patil','Male',43,'Bengaluru','Karnataka','2024-08-10');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (347,'Amit Singh','Male',22,'Pune','Maharashtra','2024-04-10');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (348,'Rohan Singh','Male',44,'Delhi','Delhi','2023-11-12');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (349,'Anjali Mehta','Female',32,'Mumbai','Maharashtra','2023-06-12');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (350,'Rohan Kumar','Male',53,'Mumbai','Maharashtra','2023-05-27');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (351,'Rohan Patel','Male',41,'Ahmedabad','Gujarat','2023-06-27');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (352,'Karan Singh','Male',56,'Hyderabad','Telangana','2023-09-07');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (353,'Neha Sharma','Female',29,'Mumbai','Maharashtra','2024-11-18');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (354,'Rohan Kumar','Male',42,'Pune','Maharashtra','2024-04-26');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (355,'Rohan Mehta','Male',51,'Ahmedabad','Gujarat','2023-10-16');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (356,'Pooja Joshi','Female',56,'Ahmedabad','Gujarat','2023-05-01');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (357,'Priya Jain','Female',53,'Chennai','Tamil Nadu','2024-06-21');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (358,'Rohan Joshi','Male',23,'Mumbai','Maharashtra','2023-11-25');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (359,'Vikas Mehta','Male',58,'Ahmedabad','Gujarat','2024-01-21');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (360,'Neha Gupta','Female',27,'Pune','Maharashtra','2023-09-08');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (361,'Pooja Verma','Female',50,'Ahmedabad','Gujarat','2023-02-23');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (362,'Kavya Patel','Female',39,'Bengaluru','Karnataka','2024-07-12');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (363,'Arjun Joshi','Male',43,'Bengaluru','Karnataka','2023-03-12');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (364,'Karan Joshi','Male',46,'Delhi','Delhi','2023-08-16');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (365,'Anjali Patel','Female',53,'Pune','Maharashtra','2023-04-11');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (366,'Amit Patel','Male',38,'Jaipur','Rajasthan','2023-01-01');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (367,'Sneha Gupta','Female',31,'Mumbai','Maharashtra','2023-11-29');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (368,'Priya Kumar','Female',45,'Jaipur','Rajasthan','2024-06-27');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (369,'Amit Patil','Male',39,'Bengaluru','Karnataka','2023-02-16');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (370,'Rahul Kumar','Male',40,'Chennai','Tamil Nadu','2023-11-12');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (371,'Pooja Singh','Female',32,'Jaipur','Rajasthan','2023-07-31');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (372,'Vikas Sharma','Male',42,'Bengaluru','Karnataka','2023-11-20');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (373,'Pooja Sharma','Female',55,'Delhi','Delhi','2024-10-12');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (374,'Sneha Jain','Female',23,'Bengaluru','Karnataka','2023-07-16');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (375,'Arjun Patel','Male',37,'Hyderabad','Telangana','2023-11-17');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (376,'Rohan Singh','Male',46,'Chennai','Tamil Nadu','2024-03-31');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (377,'Priya Singh','Female',27,'Bengaluru','Karnataka','2023-11-11');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (378,'Kavya Verma','Female',35,'Hyderabad','Telangana','2023-07-05');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (379,'Karan Gupta','Male',53,'Hyderabad','Telangana','2024-01-17');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (380,'Priya Mehta','Female',31,'Bengaluru','Karnataka','2023-11-05');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (381,'Arjun Verma','Male',60,'Hyderabad','Telangana','2023-05-16');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (382,'Arjun Patel','Male',48,'Jaipur','Rajasthan','2023-03-20');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (383,'Karan Patel','Male',58,'Mumbai','Maharashtra','2023-01-08');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (384,'Anjali Gupta','Female',56,'Hyderabad','Telangana','2024-03-09');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (385,'Priya Singh','Female',35,'Hyderabad','Telangana','2023-07-14');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (386,'Amit Gupta','Male',29,'Mumbai','Maharashtra','2023-07-10');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (387,'Rahul Mehta','Male',44,'Jaipur','Rajasthan','2024-08-21');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (388,'Rahul Kumar','Male',24,'Mumbai','Maharashtra','2023-07-04');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (389,'Karan Patil','Male',50,'Chennai','Tamil Nadu','2024-11-05');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (390,'Rahul Jain','Male',60,'Hyderabad','Telangana','2024-06-01');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (391,'Arjun Jain','Male',30,'Delhi','Delhi','2024-08-31');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (392,'Priya Mehta','Female',48,'Ahmedabad','Gujarat','2023-08-29');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (393,'Karan Gupta','Male',51,'Bengaluru','Karnataka','2023-09-23');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (394,'Karan Verma','Male',22,'Jaipur','Rajasthan','2023-09-25');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (395,'Sneha Mehta','Female',48,'Mumbai','Maharashtra','2024-08-09');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (396,'Amit Patil','Male',21,'Delhi','Delhi','2024-09-14');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (397,'Anjali Kumar','Female',48,'Ahmedabad','Gujarat','2024-05-30');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (398,'Kavya Gupta','Female',27,'Mumbai','Maharashtra','2023-03-16');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (399,'Amit Mehta','Male',29,'Bengaluru','Karnataka','2024-09-30');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (400,'Rahul Gupta','Male',40,'Ahmedabad','Gujarat','2023-02-13');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (401,'Anjali Jain','Female',51,'Hyderabad','Telangana','2024-08-25');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (402,'Priya Jain','Female',36,'Delhi','Delhi','2024-01-23');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (403,'Sneha Singh','Female',58,'Jaipur','Rajasthan','2024-11-05');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (404,'Pooja Sharma','Female',49,'Chennai','Tamil Nadu','2024-02-25');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (405,'Neha Verma','Female',51,'Mumbai','Maharashtra','2023-05-12');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (406,'Anjali Singh','Female',53,'Delhi','Delhi','2024-04-11');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (407,'Kavya Sharma','Female',46,'Mumbai','Maharashtra','2023-09-04');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (408,'Karan Singh','Male',55,'Pune','Maharashtra','2024-02-07');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (409,'Vikas Kumar','Male',22,'Ahmedabad','Gujarat','2023-03-20');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (410,'Arjun Mehta','Male',36,'Bengaluru','Karnataka','2023-10-30');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (411,'Priya Jain','Female',49,'Bengaluru','Karnataka','2024-03-04');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (412,'Priya Verma','Female',41,'Chennai','Tamil Nadu','2023-11-13');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (413,'Anjali Verma','Female',45,'Mumbai','Maharashtra','2023-06-14');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (414,'Anjali Sharma','Female',57,'Chennai','Tamil Nadu','2024-08-04');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (415,'Amit Kumar','Male',44,'Ahmedabad','Gujarat','2023-08-07');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (416,'Rohan Sharma','Male',42,'Bengaluru','Karnataka','2024-03-04');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (417,'Sneha Singh','Female',33,'Delhi','Delhi','2024-05-06');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (418,'Rohan Verma','Male',50,'Jaipur','Rajasthan','2023-11-12');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (419,'Pooja Kumar','Female',33,'Delhi','Delhi','2024-05-13');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (420,'Karan Joshi','Male',23,'Ahmedabad','Gujarat','2023-03-16');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (421,'Kavya Gupta','Female',59,'Chennai','Tamil Nadu','2023-10-09');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (422,'Rahul Jain','Male',52,'Delhi','Delhi','2023-09-26');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (423,'Rohan Mehta','Male',26,'Bengaluru','Karnataka','2023-10-03');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (424,'Neha Sharma','Female',28,'Delhi','Delhi','2024-01-04');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (425,'Sneha Patel','Female',44,'Mumbai','Maharashtra','2023-11-26');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (426,'Pooja Patel','Female',36,'Ahmedabad','Gujarat','2023-11-30');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (427,'Karan Sharma','Male',58,'Hyderabad','Telangana','2024-02-08');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (428,'Sneha Kumar','Female',29,'Mumbai','Maharashtra','2023-07-12');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (429,'Karan Mehta','Male',33,'Delhi','Delhi','2023-02-02');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (430,'Vikas Joshi','Male',54,'Ahmedabad','Gujarat','2024-05-05');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (431,'Kavya Singh','Female',48,'Hyderabad','Telangana','2023-11-18');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (432,'Arjun Joshi','Male',37,'Delhi','Delhi','2023-07-29');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (433,'Karan Kumar','Male',44,'Ahmedabad','Gujarat','2023-05-20');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (434,'Karan Patil','Male',38,'Bengaluru','Karnataka','2023-04-16');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (435,'Neha Patil','Female',22,'Bengaluru','Karnataka','2023-05-24');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (436,'Rahul Kumar','Male',24,'Mumbai','Maharashtra','2023-11-02');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (437,'Sneha Jain','Female',27,'Chennai','Tamil Nadu','2024-11-13');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (438,'Neha Verma','Female',47,'Hyderabad','Telangana','2023-04-03');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (439,'Priya Joshi','Female',51,'Jaipur','Rajasthan','2023-03-03');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (440,'Rohan Patil','Male',37,'Hyderabad','Telangana','2024-05-24');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (441,'Sneha Singh','Female',50,'Ahmedabad','Gujarat','2023-07-26');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (442,'Amit Patil','Male',25,'Bengaluru','Karnataka','2024-06-16');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (443,'Kavya Patil','Female',50,'Ahmedabad','Gujarat','2023-06-04');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (444,'Anjali Gupta','Female',45,'Hyderabad','Telangana','2023-01-24');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (445,'Priya Patil','Female',37,'Pune','Maharashtra','2024-02-19');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (446,'Rahul Joshi','Male',39,'Jaipur','Rajasthan','2024-08-22');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (447,'Pooja Patil','Female',21,'Hyderabad','Telangana','2023-03-16');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (448,'Rahul Patil','Male',56,'Chennai','Tamil Nadu','2024-01-18');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (449,'Vikas Gupta','Male',50,'Delhi','Delhi','2024-10-19');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (450,'Rohan Mehta','Male',21,'Chennai','Tamil Nadu','2024-01-07');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (451,'Anjali Verma','Female',23,'Pune','Maharashtra','2024-10-04');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (452,'Anjali Jain','Female',46,'Ahmedabad','Gujarat','2024-09-19');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (453,'Priya Gupta','Female',48,'Pune','Maharashtra','2024-04-20');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (454,'Rohan Joshi','Male',52,'Mumbai','Maharashtra','2023-05-20');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (455,'Vikas Gupta','Male',50,'Jaipur','Rajasthan','2024-01-05');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (456,'Rahul Singh','Male',34,'Bengaluru','Karnataka','2023-10-04');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (457,'Vikas Verma','Male',20,'Bengaluru','Karnataka','2024-06-17');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (458,'Karan Joshi','Male',55,'Mumbai','Maharashtra','2023-09-03');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (459,'Pooja Jain','Female',55,'Pune','Maharashtra','2024-10-01');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (460,'Kavya Patil','Female',26,'Hyderabad','Telangana','2023-12-21');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (461,'Rahul Patil','Male',30,'Bengaluru','Karnataka','2024-02-10');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (462,'Sneha Singh','Female',59,'Delhi','Delhi','2023-12-08');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (463,'Kavya Kumar','Female',46,'Hyderabad','Telangana','2024-01-14');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (464,'Vikas Patil','Male',35,'Jaipur','Rajasthan','2023-08-31');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (465,'Neha Patil','Female',28,'Delhi','Delhi','2024-06-10');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (466,'Priya Patel','Female',27,'Pune','Maharashtra','2023-11-14');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (467,'Pooja Jain','Female',30,'Jaipur','Rajasthan','2023-02-11');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (468,'Anjali Joshi','Female',42,'Jaipur','Rajasthan','2023-02-24');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (469,'Vikas Joshi','Male',60,'Ahmedabad','Gujarat','2023-09-17');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (470,'Vikas Patil','Male',41,'Chennai','Tamil Nadu','2023-07-07');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (471,'Sneha Mehta','Female',46,'Delhi','Delhi','2024-08-04');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (472,'Arjun Singh','Male',28,'Hyderabad','Telangana','2023-06-14');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (473,'Sneha Joshi','Female',31,'Hyderabad','Telangana','2023-08-25');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (474,'Rahul Kumar','Male',37,'Delhi','Delhi','2023-10-02');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (475,'Rohan Gupta','Male',28,'Ahmedabad','Gujarat','2024-01-31');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (476,'Rahul Singh','Male',32,'Pune','Maharashtra','2023-02-13');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (477,'Vikas Patil','Male',41,'Pune','Maharashtra','2024-02-19');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (478,'Rahul Jain','Male',43,'Jaipur','Rajasthan','2023-06-25');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (479,'Priya Gupta','Female',38,'Jaipur','Rajasthan','2024-10-27');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (480,'Sneha Joshi','Female',56,'Ahmedabad','Gujarat','2023-05-26');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (481,'Rohan Verma','Male',48,'Hyderabad','Telangana','2023-05-31');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (482,'Amit Patel','Male',47,'Hyderabad','Telangana','2024-05-14');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (483,'Priya Singh','Female',37,'Chennai','Tamil Nadu','2023-01-20');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (484,'Anjali Mehta','Female',60,'Delhi','Delhi','2023-10-08');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (485,'Rohan Gupta','Male',25,'Chennai','Tamil Nadu','2023-08-22');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (486,'Pooja Verma','Female',36,'Chennai','Tamil Nadu','2024-07-18');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (487,'Karan Sharma','Male',20,'Delhi','Delhi','2023-03-07');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (488,'Vikas Patel','Male',41,'Mumbai','Maharashtra','2023-07-06');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (489,'Pooja Singh','Female',50,'Bengaluru','Karnataka','2024-02-23');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (490,'Rahul Joshi','Male',45,'Chennai','Tamil Nadu','2024-07-27');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (491,'Karan Sharma','Male',59,'Bengaluru','Karnataka','2024-07-17');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (492,'Arjun Mehta','Male',32,'Hyderabad','Telangana','2023-10-11');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (493,'Vikas Verma','Male',23,'Jaipur','Rajasthan','2024-08-07');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (494,'Amit Sharma','Male',27,'Delhi','Delhi','2024-07-05');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (495,'Arjun Patel','Male',21,'Hyderabad','Telangana','2024-01-03');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (496,'Karan Gupta','Male',49,'Pune','Maharashtra','2024-06-10');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (497,'Rahul Verma','Male',20,'Pune','Maharashtra','2024-01-09');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (498,'Karan Gupta','Male',45,'Bengaluru','Karnataka','2024-05-21');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (499,'Vikas Jain','Male',45,'Pune','Maharashtra','2024-05-08');
INSERT INTO customers (custid,custname,gender,age,city,state,joindate) VALUES (500,'Kavya Joshi','Female',21,'Hyderabad','Telangana','2024-09-30');
